import { createPool } from "mysql2/promise";
const url = process.env.DATABASE_URL;
const pool = createPool({ uri: url, ssl: { rejectUnauthorized: false } });
const conn = await pool.getConnection();
const [cols] = await conn.query("SHOW COLUMNS FROM users");
console.log("users columns:", cols.map(c => c.Field).join(", "));
const [tables] = await conn.query("SHOW TABLES");
console.log("\nAll tables:", tables.map(t => Object.values(t)[0]).join(", "));
conn.release();
await pool.end();
