CREATE TABLE IF NOT EXISTS `social_post_library` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` ENUM('aaus','iheartecho') NOT NULL DEFAULT 'aaus',
  `headline` VARCHAR(512) NOT NULL,
  `body` TEXT NOT NULL,
  `subtext` TEXT NULL,
  `socialCaption` TEXT NOT NULL,
  `category` VARCHAR(128) NOT NULL,
  `contentType` VARCHAR(64) NOT NULL,
  `layoutMode` ENUM('card','infographic') NOT NULL DEFAULT 'card',
  `cardTheme` ENUM('dark','light') NOT NULL DEFAULT 'light',
  `imageUrl` TEXT NULL,
  `imageSource` ENUM('ai','upload','media_repository','google') NULL DEFAULT 'ai',
  `mediaAssetId` INT NULL,
  `imageOriginalUrl` TEXT NULL,
  `imageSourcePageUrl` TEXT NULL,
  `imageAttribution` TEXT NULL,
  `imageLicense` VARCHAR(255) NULL,
  `createdByUserId` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `social_post_library_brand_created_idx` (`brand`, `createdAt`),
  KEY `social_post_library_creator_idx` (`createdByUserId`)
);
