-- Sync lms_courses schema on Railway MySQL after Manus TiDB mirror.
-- Manus TiDB was missing many columns that the current app expects.
-- Run once against Railway MySQL: Railway → MySQL-UltrasoundAssist → Connect
-- (Also applied automatically on app startup via ensureLmsCoursesSchema.ts)

ALTER TABLE `lms_courses`
  MODIFY COLUMN `status` ENUM('draft','public','hidden','private','archived','enrollment_closed','waitlist','presale') NOT NULL DEFAULT 'draft',
  MODIFY COLUMN `type` ENUM('course','quiz','download','cohort','workshop') NOT NULL DEFAULT 'course',
  MODIFY COLUMN `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00;

ALTER TABLE `lms_courses`
  ADD COLUMN IF NOT EXISTS `enrollment_close_date` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `bundle_only` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `meta_keywords` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `certificate_template_id` INT NULL,
  ADD COLUMN IF NOT EXISTS `credit_hours` VARCHAR(16) NULL,
  ADD COLUMN IF NOT EXISTS `certificate_title_override` VARCHAR(512) NULL,
  ADD COLUMN IF NOT EXISTS `show_instructor` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `hide_progress` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `show_in_library` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `course_overview_top_blocks` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `course_overview_blocks` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `course_overview_bottom_blocks` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `send_enrollment_email` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `custom_thank_you_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `custom_thank_you_blocks` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `post_purchase_redirect_url` VARCHAR(1024) NULL,
  ADD COLUMN IF NOT EXISTS `welcome_email_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `welcome_email_subject` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `welcome_email_body` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `hide_pricing_options` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `upsell_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `upsell_course_id` INT NULL,
  ADD COLUMN IF NOT EXISTS `upsell_product_type` VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS `upsell_product_id` INT NULL,
  ADD COLUMN IF NOT EXISTS `upsell_headline` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `upsell_description` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `completion_redirect_url` VARCHAR(1024) NULL,
  ADD COLUMN IF NOT EXISTS `completion_email_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `completion_email_subject` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `completion_email_body` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `primary_color` VARCHAR(20) DEFAULT '#179ca3',
  ADD COLUMN IF NOT EXISTS `accent_color` VARCHAR(20) DEFAULT '#0d9488',
  ADD COLUMN IF NOT EXISTS `gradient_from` VARCHAR(20) DEFAULT '#179ca3',
  ADD COLUMN IF NOT EXISTS `gradient_to` VARCHAR(20) DEFAULT '#0d9488',
  ADD COLUMN IF NOT EXISTS `gradient_direction` VARCHAR(30) DEFAULT '135deg',
  ADD COLUMN IF NOT EXISTS `thumbnail_url` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `custom_labels` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `default_mark_complete` INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `player_theme` ENUM('light','dark') NOT NULL DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS `allow_group_purchase` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `library_order` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `publish_domain` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `multi_cohort_mode` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `waitlist_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `waitlist_heading` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `waitlist_body` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `waitlist_cta_label` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `waitlist_cta_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `waitlist_redirect_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `waitlist_success_message` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `presale_welcome_heading` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `presale_welcome_body` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `presale_welcome_media_url` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `presale_welcome_cta_label` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `presale_welcome_cta_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `player_sidebar_blocks` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `purchase_terms_text` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `purchase_terms_link_text_1` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `purchase_terms_link_url_1` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `purchase_terms_link_text_2` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `purchase_terms_link_url_2` VARCHAR(2048) NULL;
