import { useMemo, useState } from "react";
import { Link } from "wouter";
import { BarChart3, CheckCircle2, FileText, Flag, Megaphone, Plus, Save, Trash2, UserMinus, UserPlus, Users } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { BlockPreview } from "@/components/BlockPreview";
import { toast } from "sonner";

function safeParse(value?: string) { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }

type ReportContentType = "document" | "message" | "task" | "module";

export default function StudyGroupsAdmin() {
  const utils = trpc.useUtils();
  const { data: groups, isLoading } = trpc.studyGroups.adminListGroups.useQuery();
  const { data: workspace } = trpc.studyGroups.getWorkspaceBlocks.useQuery();
  const [blocks, setBlocks] = useState<any[] | null>(null);
  const [selectedGroupId, setSelectedGroupId] = useState<number | null>(null);
  const [inviteEmail, setInviteEmail] = useState("");
  const [deleteName, setDeleteName] = useState("");
  const currentBlocks = blocks ?? safeParse(workspace?.blocksJson);
  const selectedGroup = groups?.find(group => group.id === selectedGroupId) ?? null;
  const invalidateAdminGroups = () => void utils.studyGroups.adminListGroups.invalidate();
  const save = trpc.studyGroups.saveWorkspaceBlocks.useMutation({ onSuccess: () => { toast.success("Study Group workspace blocks saved"); setBlocks(null); void utils.studyGroups.getWorkspaceBlocks.invalidate(); }, onError: e => toast.error(e.message) });
  const invite = trpc.studyGroups.inviteByEmail.useMutation({ onSuccess: () => { toast.success("Invitation sent"); setInviteEmail(""); invalidateAdminGroups(); }, onError: e => toast.error(e.message) });
  const revokeMember = trpc.studyGroups.revokeMember.useMutation({ onSuccess: () => { toast.success("Member access revoked"); invalidateAdminGroups(); }, onError: e => toast.error(e.message) });
  const deleteContent = trpc.studyGroups.adminDeleteContent.useMutation({ onSuccess: () => { toast.success("Group content removed"); invalidateAdminGroups(); }, onError: e => toast.error(e.message) });
  const resolveReport = trpc.studyGroups.adminResolveContentReport.useMutation({ onSuccess: () => { toast.success("Content report updated"); invalidateAdminGroups(); }, onError: e => toast.error(e.message) });
  const deleteGroup = trpc.studyGroups.adminDeleteGroup.useMutation({ onSuccess: () => { toast.success("Study Group deleted"); setSelectedGroupId(null); setDeleteName(""); invalidateAdminGroups(); }, onError: e => toast.error(e.message) });
  const activeGroups = groups?.filter(group => group.status === "active").length ?? 0;
  const totalMembers = groups?.reduce((sum, group) => sum + group.activeMembers, 0) ?? 0;
  const totalDocuments = groups?.reduce((sum, group) => sum + group.documents.length, 0) ?? 0;
  const openReports = groups?.flatMap(group => group.reports.filter(report => report.status === "open" || report.status === "reviewing").map(report => ({ ...report, groupName: group.name }))) ?? [];
  const updateBlock = (index: number, patch: Record<string, unknown>) => setBlocks(currentBlocks.map((block, current) => current === index ? { ...block, data: { ...(block.data || {}), ...patch } } : block));
  const removeBlock = (index: number) => setBlocks(currentBlocks.filter((_, current) => current !== index));
  const addText = () => setBlocks([...currentBlocks, { id: `study-group-text-${Date.now()}`, type: "text", data: { content: "<p>New Study Group announcement</p>" } }]);
  const addCta = () => setBlocks([...currentBlocks, { id: `study-group-cta-${Date.now()}`, type: "cta", data: { title: "Continue learning", description: "Explore current learning opportunities.", buttonText: "Open Education Library", buttonUrl: "/education-library", style: "teal" } }]);
  const removeReportedItem = (report: { groupId: number; contentType: ReportContentType; contentId: number; id: number }) => {
    if (!confirm(`Remove this reported ${report.contentType} from the Study Group? This cannot be undone.`)) return;
    deleteContent.mutate({ groupId: report.groupId, contentType: report.contentType, contentId: report.contentId }, {
      onSuccess: () => resolveReport.mutate({ reportId: report.id, status: "resolved", resolutionNote: `Removed ${report.contentType} from the group.` }),
    });
  };

  return <div className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-7">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-teal-700">Platform Admin</p><h1 className="text-3xl font-bold text-slate-900">Study Groups oversight</h1><p className="mt-1 max-w-3xl text-sm text-slate-600">Review all private groups, membership access, shared content, and member safety reports. This administrative oversight is not advertised to learners.</p></div><Link href="/platform-admin"><Button variant="outline">Return to Platform Admin</Button></Link></div>
    <div className="grid gap-4 md:grid-cols-4"><Card><CardHeader className="pb-2"><Users className="h-5 w-5 text-teal-600" /><CardDescription>Active groups</CardDescription><CardTitle>{activeGroups}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><BarChart3 className="h-5 w-5 text-indigo-600" /><CardDescription>Active participants</CardDescription><CardTitle>{totalMembers}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><FileText className="h-5 w-5 text-amber-600" /><CardDescription>Visible uploads</CardDescription><CardTitle>{totalDocuments}</CardTitle></CardHeader></Card><Card className={openReports.length ? "border-rose-200 bg-rose-50" : ""}><CardHeader className="pb-2"><Flag className={`h-5 w-5 ${openReports.length ? "text-rose-600" : "text-teal-600"}`} /><CardDescription>Open content reports</CardDescription><CardTitle>{openReports.length}</CardTitle></CardHeader></Card></div>

    <Card className={openReports.length ? "border-rose-200" : "border-slate-200"}><CardHeader><CardTitle className="flex items-center gap-2"><Flag className="h-5 w-5 text-rose-600" />Reported content</CardTitle><CardDescription>Member reports are private to Platform Admins. New reports also send an owner notification for prompt review.</CardDescription></CardHeader><CardContent className="space-y-3">{openReports.map(report => <div key={report.id} className="rounded-lg border border-rose-100 bg-rose-50/60 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{report.groupName}</p><Badge variant="outline">{report.contentType}</Badge><Badge className={report.status === "open" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-800"}>{report.status}</Badge></div><p className="mt-2 text-sm text-slate-800"><strong>Reason:</strong> {report.reason}</p>{report.details && <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{report.details}</p>}<p className="mt-2 text-xs text-slate-500">Reported by {report.reporterName} · {new Date(report.createdAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={resolveReport.isPending} onClick={() => resolveReport.mutate({ reportId: report.id, status: "reviewing" })}>Mark reviewing</Button><Button size="sm" variant="outline" disabled={resolveReport.isPending} onClick={() => resolveReport.mutate({ reportId: report.id, status: "dismissed" })}>Dismiss</Button><Button size="sm" className="bg-rose-600 hover:bg-rose-700" disabled={deleteContent.isPending || resolveReport.isPending} onClick={() => removeReportedItem(report)}>Remove content</Button></div></div></div>)}{!openReports.length && <div className="rounded-lg border border-dashed border-teal-200 bg-teal-50 p-6 text-center text-sm text-teal-800"><CheckCircle2 className="mx-auto mb-2 h-5 w-5" />No Study Group content is awaiting review.</div>}</CardContent></Card>

    <Card><CardHeader><CardTitle>All groups</CardTitle><CardDescription>Select a group to manage access, inspect documents and purchased content, or remove a group where appropriate.</CardDescription></CardHeader><CardContent className="space-y-3">{isLoading && <p className="text-sm text-slate-500">Loading groups…</p>}{groups?.map(group => <div key={group.id} className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{group.name}</p>{group.tier === "organization" && <Badge className="bg-amber-100 text-amber-800">Organization</Badge>}<Badge variant="secondary">{group.status}</Badge>{group.reports.some(report => report.status === "open" || report.status === "reviewing") && <Badge className="bg-rose-100 text-rose-800"><Flag className="mr-1 h-3 w-3" />Needs review</Badge>}</div><p className="mt-1 text-sm text-slate-500">{group.organizationName || "Independent learner group"} · {group.activeMembers} active participant{group.activeMembers === 1 ? "" : "s"} · {group.documents.length} document{group.documents.length === 1 ? "" : "s"} · {group.contentAccesses.length} group content item{group.contentAccesses.length === 1 ? "" : "s"}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setSelectedGroupId(group.id)}>Manage</Button><Link href={`/study-groups/${group.id}`}><Button variant="outline">Review workspace</Button></Link></div></div>)}{!isLoading && !groups?.length && <p className="py-8 text-center text-sm text-slate-500">No Study Groups have been created yet.</p>}</CardContent></Card>

    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Megaphone className="h-5 w-5 text-teal-600" />Workspace content blocks</CardTitle><CardDescription>These editable blocks appear within every Study Group workspace. Use them for announcements, optional advertisements, resources, or calls to action.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={addText}><Plus className="mr-2 h-4 w-4" />Text</Button><Button variant="outline" onClick={addCta}><Plus className="mr-2 h-4 w-4" />CTA</Button></div></div></CardHeader><CardContent className="space-y-4">{currentBlocks.map((block, index) => <div key={block.id || index} className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><Badge variant="secondary">{block.type}</Badge><Button size="sm" variant="ghost" className="text-rose-600" onClick={() => removeBlock(index)}>Remove</Button></div>{block.type === "text" && <Textarea value={block.data?.content || ""} onChange={event => updateBlock(index, { content: event.target.value })} className="min-h-28 font-mono text-xs" />}{block.type === "cta" && <div className="grid gap-3 md:grid-cols-2"><Input value={block.data?.title || ""} onChange={event => updateBlock(index, { title: event.target.value })} placeholder="Headline" /><Input value={block.data?.buttonText || ""} onChange={event => updateBlock(index, { buttonText: event.target.value })} placeholder="Button label" /><Textarea value={block.data?.description || ""} onChange={event => updateBlock(index, { description: event.target.value })} placeholder="Description" /><Input value={block.data?.buttonUrl || ""} onChange={event => updateBlock(index, { buttonUrl: event.target.value })} placeholder="Button URL" /></div>}<div className="mt-4 rounded border bg-slate-50 p-3"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Preview</p><BlockPreview block={block} /></div></div>)}{!currentBlocks.length && <div className="rounded-lg border border-dashed p-8 text-center text-sm text-slate-500">No global workspace blocks yet. Add a text or CTA block to publish a useful message to Study Groups.</div>}<Button disabled={save.isPending} className="bg-teal-600 hover:bg-teal-700" onClick={() => save.mutate({ blocksJson: JSON.stringify(currentBlocks) })}><Save className="mr-2 h-4 w-4" />{save.isPending ? "Saving…" : "Save workspace blocks"}</Button></CardContent></Card>

    <Dialog open={Boolean(selectedGroup)} onOpenChange={(open) => { if (!open) { setSelectedGroupId(null); setInviteEmail(""); setDeleteName(""); } }}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{selectedGroup?.name || "Study Group"} — administrative management</DialogTitle><DialogDescription>Platform Admin controls override group-admin access for support, safeguarding, and removal actions.</DialogDescription></DialogHeader>{selectedGroup && <div className="space-y-6"><section><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-slate-900">Members and access</h3><Badge variant="secondary">{selectedGroup.activeMembers} active</Badge></div><div className="max-h-64 space-y-2 overflow-y-auto rounded-lg border border-slate-200 p-3">{selectedGroup.members.map(member => <div key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-slate-100 p-3"><div><p className="text-sm font-medium text-slate-800">{member.displayName}</p><p className="text-xs text-slate-500">{member.email}</p></div><div className="flex items-center gap-2"><Badge variant={member.inviteStatus === "active" ? "secondary" : "outline"}>{member.role.replace("_", " ")} · {member.inviteStatus}</Badge>{member.role !== "owner" && member.inviteStatus !== "revoked" && <Button size="sm" variant="outline" className="text-rose-700" disabled={revokeMember.isPending} onClick={() => revokeMember.mutate({ groupId: selectedGroup.id, memberId: member.id })}><UserMinus className="mr-1 h-3.5 w-3.5" />Revoke</Button>}</div></div>)}{!selectedGroup.members.length && <p className="p-3 text-sm text-slate-500">No members are recorded for this group.</p>}</div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input type="email" value={inviteEmail} onChange={event => setInviteEmail(event.target.value)} placeholder="Existing learner email address" /><Button disabled={!inviteEmail.includes("@") || invite.isPending} className="shrink-0 bg-teal-600 hover:bg-teal-700" onClick={() => invite.mutate({ groupId: selectedGroup.id, email: inviteEmail, origin: window.location.origin })}><UserPlus className="mr-2 h-4 w-4" />{invite.isPending ? "Sending…" : "Invite member"}</Button></div></section>
      <section><h3 className="mb-3 font-semibold text-slate-900">Shared documents</h3><div className="space-y-2">{selectedGroup.documents.map(document => <div key={document.id} className="flex items-center justify-between gap-3 rounded-md border border-slate-200 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{document.title}</p><p className="text-xs text-slate-500">{Math.ceil(document.fileSize / 1024)} KB · uploaded {new Date(document.createdAt).toLocaleDateString()}</p></div><Button size="sm" variant="outline" className="text-rose-700" disabled={deleteContent.isPending} onClick={() => { if (confirm(`Remove “${document.title}” from this group?`)) deleteContent.mutate({ groupId: selectedGroup.id, contentType: "document", contentId: document.id }); }}><Trash2 className="mr-1 h-3.5 w-3.5" />Delete</Button></div>)}{!selectedGroup.documents.length && <p className="rounded-md border border-dashed p-3 text-sm text-slate-500">No shared documents.</p>}</div></section>
      <section><h3 className="mb-3 font-semibold text-slate-900">Group content access</h3><div className="space-y-2">{selectedGroup.contentAccesses.map(access => <div key={access.id} className="rounded-md border border-slate-200 p-3"><p className="text-sm font-medium text-slate-800">{access.contentTitle}</p><p className="mt-1 text-xs text-slate-500">{access.contentType} · {access.seatLimit} purchased seat{access.seatLimit === 1 ? "" : "s"} · {access.status}</p></div>)}{!selectedGroup.contentAccesses.length && <p className="rounded-md border border-dashed p-3 text-sm text-slate-500">No group content purchases.</p>}</div></section>
      <section className="rounded-lg border border-rose-200 bg-rose-50 p-4"><h3 className="font-semibold text-rose-900">Delete this Study Group</h3><p className="mt-1 text-sm text-rose-800">This permanently removes group membership, discussion, tasks, modules, documents, reports, and group-content records. Private document objects remain retained only for audit consistency. Active Organization subscriptions must be canceled or archived first.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input value={deleteName} onChange={event => setDeleteName(event.target.value)} placeholder={`Type “${selectedGroup.name}” to confirm`} /><Button variant="destructive" disabled={deleteName !== selectedGroup.name || deleteGroup.isPending} onClick={() => deleteGroup.mutate({ groupId: selectedGroup.id, confirmName: deleteName })}>{deleteGroup.isPending ? "Deleting…" : "Delete group"}</Button></div></section>
    </div>}<DialogFooter><Button variant="outline" onClick={() => setSelectedGroupId(null)}>Close</Button></DialogFooter></DialogContent></Dialog>
  </div></div>;
}
