import { useMemo, useState } from "react";
import { Link } from "wouter";
import { BarChart3, FileText, Megaphone, Plus, Save, Users } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { BlockPreview } from "@/components/BlockPreview";
import { toast } from "sonner";

function safeParse(value?: string) { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }

export default function StudyGroupsAdmin() {
  const utils = trpc.useUtils();
  const { data: groups, isLoading } = trpc.studyGroups.adminListGroups.useQuery();
  const { data: workspace } = trpc.studyGroups.getWorkspaceBlocks.useQuery();
  const [blocks, setBlocks] = useState<any[] | null>(null);
  const currentBlocks = blocks ?? safeParse(workspace?.blocksJson);
  const save = trpc.studyGroups.saveWorkspaceBlocks.useMutation({ onSuccess: () => { toast.success("Study Group workspace blocks saved"); setBlocks(null); void utils.studyGroups.getWorkspaceBlocks.invalidate(); }, onError: e => toast.error(e.message) });
  const activeGroups = groups?.filter(group => group.status === "active").length ?? 0;
  const totalMembers = groups?.reduce((sum, group) => sum + group.activeMembers, 0) ?? 0;
  const totalDocuments = groups?.reduce((sum, group) => sum + group.documents.length, 0) ?? 0;
  const updateBlock = (index: number, patch: Record<string, unknown>) => setBlocks(currentBlocks.map((block, current) => current === index ? { ...block, data: { ...(block.data || {}), ...patch } } : block));
  const removeBlock = (index: number) => setBlocks(currentBlocks.filter((_, current) => current !== index));
  const addText = () => setBlocks([...currentBlocks, { id: `study-group-text-${Date.now()}`, type: "text", data: { content: "<p>New Study Group announcement</p>" } }]);
  const addCta = () => setBlocks([...currentBlocks, { id: `study-group-cta-${Date.now()}`, type: "cta", data: { title: "Continue learning", description: "Explore current learning opportunities.", buttonText: "Open Education Library", buttonUrl: "/education-library", style: "teal" } }]);

  return <div className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-teal-700">Platform Admin</p><h1 className="text-3xl font-bold text-slate-900">Study Groups oversight</h1><p className="mt-1 max-w-3xl text-sm text-slate-600">Review all private group activity and document uploads for safeguarding and support. This administrative oversight is not advertised to learners.</p></div><Link href="/platform-admin"><Button variant="outline">Return to Platform Admin</Button></Link></div>
    <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><Users className="h-5 w-5 text-teal-600" /><CardDescription>Active groups</CardDescription><CardTitle>{activeGroups}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><BarChart3 className="h-5 w-5 text-indigo-600" /><CardDescription>Active participants</CardDescription><CardTitle>{totalMembers}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><FileText className="h-5 w-5 text-amber-600" /><CardDescription>Visible uploads</CardDescription><CardTitle>{totalDocuments}</CardTitle></CardHeader></Card></div>
    <Card><CardHeader><CardTitle>All groups</CardTitle><CardDescription>Open a group to review the same private workspace and activity records available to Platform Admins.</CardDescription></CardHeader><CardContent className="space-y-3">{isLoading && <p className="text-sm text-slate-500">Loading groups…</p>}{groups?.map(group => <div key={group.id} className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{group.name}</p>{group.tier === "organization" && <Badge className="bg-amber-100 text-amber-800">Organization</Badge>}<Badge variant="secondary">{group.status}</Badge></div><p className="mt-1 text-sm text-slate-500">{group.organizationName || "Independent learner group"} · {group.activeMembers} active participant{group.activeMembers === 1 ? "" : "s"} · {group.documents.length} document{group.documents.length === 1 ? "" : "s"}</p></div><Link href={`/study-groups/${group.id}`}><Button variant="outline">Review workspace</Button></Link></div>)}{!isLoading && !groups?.length && <p className="py-8 text-center text-sm text-slate-500">No Study Groups have been created yet.</p>}</CardContent></Card>
    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Megaphone className="h-5 w-5 text-teal-600" />Workspace content blocks</CardTitle><CardDescription>These editable blocks appear within every Study Group workspace. Use them for announcements, optional advertisements, resources, or calls to action.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={addText}><Plus className="mr-2 h-4 w-4" />Text</Button><Button variant="outline" onClick={addCta}><Plus className="mr-2 h-4 w-4" />CTA</Button></div></div></CardHeader><CardContent className="space-y-4">{currentBlocks.map((block, index) => <div key={block.id || index} className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><Badge variant="secondary">{block.type}</Badge><Button size="sm" variant="ghost" className="text-rose-600" onClick={() => removeBlock(index)}>Remove</Button></div>{block.type === "text" && <Textarea value={block.data?.content || ""} onChange={event => updateBlock(index, { content: event.target.value })} className="min-h-28 font-mono text-xs" />}{block.type === "cta" && <div className="grid gap-3 md:grid-cols-2"><Input value={block.data?.title || ""} onChange={event => updateBlock(index, { title: event.target.value })} placeholder="Headline" /><Input value={block.data?.buttonText || ""} onChange={event => updateBlock(index, { buttonText: event.target.value })} placeholder="Button label" /><Textarea value={block.data?.description || ""} onChange={event => updateBlock(index, { description: event.target.value })} placeholder="Description" /><Input value={block.data?.buttonUrl || ""} onChange={event => updateBlock(index, { buttonUrl: event.target.value })} placeholder="Button URL" /></div>}<div className="mt-4 rounded border bg-slate-50 p-3"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Preview</p><BlockPreview block={block} /></div></div>)}{!currentBlocks.length && <div className="rounded-lg border border-dashed p-8 text-center text-sm text-slate-500">No global workspace blocks yet. Add a text or CTA block to publish a useful message to Study Groups.</div>}<Button disabled={save.isPending} className="bg-teal-600 hover:bg-teal-700" onClick={() => save.mutate({ blocksJson: JSON.stringify(currentBlocks) })}><Save className="mr-2 h-4 w-4" />{save.isPending ? "Saving…" : "Save workspace blocks"}</Button></CardContent></Card>
  </div></div>;
}
