-- SDMS CME Credit Integration tables
-- Run against MySQL when deploying this feature

CREATE TABLE IF NOT EXISTS `sdmsCmeConfigs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `activityType` enum('course','cohort','webinar','replay_course','live_event','standalone_cme') NOT NULL,
  `activityId` int NOT NULL,
  `enabled` boolean NOT NULL DEFAULT false,
  `approvalId` varchar(64),
  `activityTitle` varchar(500),
  `activityStartDate` varchar(32),
  `activityEndDate` varchar(32),
  `cmeCreditAmount` varchar(16) DEFAULT '0.00',
  `cmeCreditCategory` enum('AB_CME','AE_CME','BR_CME','FE_CME','MSK_CME','OB_CME','OT_CME','PE_CME','PS_CME','SPI_CME','VT_CME') DEFAULT 'SPI_CME',
  `speakerStatusDefault` varchar(1) DEFAULT 'N',
  `apiUsername` varchar(255),
  `apiPasswordEncrypted` text,
  `formTemplateId` int,
  `formKind` enum('post_test','evaluation','combined','attestation') DEFAULT 'combined',
  `passingScorePercent` varchar(8) DEFAULT '70',
  `submissionDeadlineDays` varchar(8) DEFAULT '90',
  `resubmissionEnabled` boolean NOT NULL DEFAULT true,
  `formFieldMapping` longtext,
  `moduleBlocks` longtext,
  `cmeInstructions` longtext,
  `sdmsBaseUrl` varchar(500),
  `createdByUserId` int,
  `updatedByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `idx_sdms_cme_config_activity` (`activityType`, `activityId`)
);

CREATE TABLE IF NOT EXISTS `sdmsCmeCompletions` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `configId` int NOT NULL,
  `userId` int NOT NULL,
  `activityType` enum('course','cohort','webinar','replay_course','live_event','standalone_cme') NOT NULL,
  `activityId` int NOT NULL,
  `formSubmissionId` int,
  `formScore` varchar(16),
  `formMaxScore` varchar(16),
  `formScorePercent` varchar(16),
  `passStatus` enum('pending','passed','failed','override_pass','override_fail') NOT NULL DEFAULT 'pending',
  `manualOverrideNotes` text,
  `manualOverrideByUserId` int,
  `dateCompleted` varchar(32),
  `learnerPayload` longtext,
  `sdmsSubmissionStatus` enum('not_submitted','pending','success','failed','timeout') NOT NULL DEFAULT 'not_submitted',
  `sdmsResponseCode` varchar(16),
  `sdmsResponseMessage` text,
  `sdmsResponseRaw` longtext,
  `certificateUrl` text,
  `certificateId` varchar(128),
  `lastSubmissionAttemptAt` timestamp NULL,
  `retryCount` int NOT NULL DEFAULT 0,
  `lastSubmittedBy` enum('system','admin'),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `sdmsCmeSubmissionLogs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `completionId` int,
  `userId` int NOT NULL,
  `activityType` enum('course','cohort','webinar','replay_course','live_event','standalone_cme') NOT NULL,
  `activityId` int NOT NULL,
  `approvalId` varchar(64),
  `payloadSent` longtext NOT NULL,
  `apiResponse` longtext,
  `responseCode` varchar(16),
  `status` enum('success','failed','timeout','simulated_success','simulated_failure','validation_error') NOT NULL,
  `retryCount` int NOT NULL DEFAULT 0,
  `triggeredBy` enum('system','admin') NOT NULL DEFAULT 'system',
  `errorMessage` text,
  `resolved` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
